development: &common
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: yoteprestoapi_development
  pool: 5
  username: gerardo_ct
  password: ''
  host: localhost

test:
  <<: *common
  database: yoteprestoapi_test
